version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
      - './src/app/code/Custom/VideoWidget/etc/module.xml:/bitnami/magento/app/code/Custom/VideoWidget/etc/module.xml'
      - './src/app/code/Custom/VideoWidget/view/frontend/layout/widget.xml:/bitnami/magento/app/code/Custom/VideoWidget/view/frontend/layout/widget.xml'
      - './src/app/code/Custom/VideoWidget/view/frontend/templates/widget/video_widget.phtml:/bitnami/magento/app/code/Custom/VideoWidget/view/frontend/templates/widget/video_widget.phtml'
      - './src/app/code/Custom/VideoWidget/view/frontend/web/js/main.js:/bitnami/magento/app/code/Custom/VideoWidget/view/frontend/web/js/main.js'
      - './src/app/code/Custom/VideoWidget/registration.php:/bitnami/magento/app/code/Custom/VideoWidget/registration.php'
      - './src/app/code/Custom/VideoWidget/Block/Widget/VideoWidget.php:/bitnami/magento/app/code/Custom/VideoWidget/Block/Widget/VideoWidget.php'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local